---
stages:
  - test

.test-matrix:
  stage: test
  image: python:${PYTHON_VERSION}-slim
  parallel:
    matrix:
      - PYTHON_VERSION:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

test-matrix:
  extends: .test-matrix
  before_script:
    - cd $CI_PROJECT_DIR
    - pip install --upgrade hatch
  script:
    - hatch env run --env test no-cov

test-matrix-cmd-line:
  extends: .test-matrix
  before_script:
    - cd $CI_PROJECT_DIR
  script:
    - pip install .
    - make_tree "(A,B,(C,D),E);"

generate-test-report:
  stage: test
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y python3 python3-pip
    - pip install --upgrade hatch
  script:
    - hatch env run --env test ci-report
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: unit_test.xml
