name: CI

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          sudo apt-get install -y libgl-dev python3-pyqt5 python3-pyqt5.qtopengl python3-pyqt5.qtsvg

      - name: Run build
        run: |
          pip3 install "."

      - name: Run test
        run: |
          pip3 install ".[testing]"
          pip3 install pytest-cov
          pytest -v \
            --junitxml=report.xml \
            --cov=make_tree tests/ \
            --cov-report=term-missing:skip-covered \
            | tee coverage.txt

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: |
            report.xml
            coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: coverage.txt
          junitxml-path: report.xml
