name: CI

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Run tests and track code coverage
        run: |
          hatch env run --env test no-cov

      - name: Run in cmd line
        run: |
          pip install .
          make_tree "(A,B,(C,D),E);" test.pdf "foo bar"
  test:
    name: Test and report on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Run tests and track code coverage
        run: |
          hatch env run --env test ci-report

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: |
            unit_test.xml
            coverage.xml

      # Not entirely sure why this is failing
      # - name: Pytest coverage comment
      #   uses: MishaKav/pytest-coverage-comment@main
      #   with:
      #     pytest-xml-coverage-path: coverage.xml
      #     junitxml-path: unit_test.xml
